// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Green Air Cannabis",
  domain: "www.greenaircannabis.com",
  city: "Mississauga",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-mississauga",
  address: "7060 Airport Rd, Mississauga, ON L4T 2G8",
  streetAddress: "7060 Airport Rd",
  postalCode: "L4T 2G8",
  phone: "+1 (289) 514-9467",
  phoneIntl: "+12895149467",
  neighborhood: "Malton / Airport",
  nearbyAreas: ["Airport Road", "Malton", "Mississauga", "Pearson Airport", "Derry Road", "Goreway Drive", "MiWay"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "https://maps.google.com/maps?q=7060+Airport+Rd,+Mississauga,+ON+L4T+2G8&z=16&output=embed",
  latitude: "43.704554",
  longitude: "-79.6443735",
  hours: ["Open 24 Hours"],
  seoTitle: "Weed Dispensary in Malton / Airport Rd",
  metaDescription: "Green Air Cannabis is the 24-hour walk-in at 7060 Airport Rd in Malton, Mississauga — Airport Road near Pearson and Derry. Adults 19+.",
  localLandmarks: ["Airport Road", "Malton", "Mississauga"],
  introVariant: "Green Air Cannabis is the 24-hour walk-in at 7060 Airport Rd in Malton, on the Airport Road strip that feeds Pearson and Derry Road. Adults 19+ can browse flower, pre-rolls, edibles, THC vapes, concentrates, and accessories. Use the homepage for current NAP and menu categories.",
  neighborhoodDescription: "Located in the vibrant Malton / Airport district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Free parking is available in the retail plaza lot",
  transitNote: "Accessible by MiWay routes serving the surrounding Mississauga area.",
  sectionTitle: "Serving Customers Near Malton and Mississauga"
};
