// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Green Air Cannabis",
  domain: "greenaircannabis.com",
  city: "Mississauga",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-mississauga",
  address: "7060 Airport Rd, Mississauga, ON L4T 2G8",
  streetAddress: "7060 Airport Rd",
  postalCode: "L4T 2G8",
  phone: "(437) 707-1207",
  phoneIntl: "+14377071207",
  neighborhood: "Malton / Airport",
  nearbyAreas: ["Airport Road", "Malton", "Mississauga", "Pearson Airport", "Derry Road", "Goreway Drive", "MiWay"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://greenaircannabis.com/",
  mapEmbedUrl: "https://maps.google.com/maps?q=Green%20Air%20Cannabis%207060%20Airport%20Rd%2C%20Mississauga%2C%20ON%20L4T%202G8&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6532",
  longitude: "-79.3832",
  hours: ["Open Daily: 10:00 AM - 02:00 AM"],
  seoTitle: "Green Air Cannabis | Weed Dispensary in Mississauga",
  metaDescription: "Green Air Cannabis is a local weed dispensary in Mississauga offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Airport Road", "Malton", "Mississauga"],
  introVariant: "Green Air Cannabis is your welcoming neighborhood weed dispensary in Mississauga, located at 7060 Airport Rd near Malton / Airport. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near Malton, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant Malton / Airport district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Free parking is available in the retail plaza lot",
  transitNote: "Accessible by MiWay routes serving the surrounding Mississauga area.",
  sectionTitle: "Serving Customers Near Malton and Mississauga"
};
